echo 'Al gener, tanca la porta i encén el braser',
echo 'Aigua de gener tot l'any va bé',
echo 'Pel febrer, carnestoltes el primer',
echo 'Pel febrer flor a l'ametler',
echo 'Mes tard o més matiner carnaval dins el febrer',
